### ISSUE TITLE
Getting client_secret or client_assertion error when authenticating

### ISSUE THREAD

**Issue by KailasamNK** [PartnerCenterSamples/Partner-Center-SDK-Samples#2]
Hi,
I got the below error when trying to authenticate the application. The request body must contain the following parameter: 'client_secret or client_assertion'. My application is web application not an native client application. Is there any code that supports web application?

**Comment by RaedJarrar** [comment]
Hello, In order to authenticate an AD web application, please use application based credentials in the samples. Almost all the samples rely on the user based authentication which requires a native application. However, you can change the code to rely on the app authentication property rather than the user authentication. This will work for most of the scenarios other than the ones that require an actively signed in user. In this case, you can choose to on-board an AD native application and use user authentication which gives more more access to the APIs.

**Comment by KailasamNK** [comment]
Hi I have used app authentication property for authentication. It supports few functions only. For ex: I can able to to create a customer, delete a customer. I need to use App authentication for all the functions. Is that support for all functions?
